Temp. Dashboard function
framgia831/rails-elearning-nozomi pull request #10
Opened 2018-09-18 01:01 UTC by nozomi-matsuoka

2018-09-19 04:27 UTC, inahsanjuan commented on app/views/admin/words/index.html.erb
> +		<% @words.in_groups_of(@words.size / 2).each do |group| %>
@nozomi-matsuoka Add a condition that checks if  `@words` variable is not empty

2018-09-19 04:46 UTC, nozomi-matsuoka commented
Implemented:
- Improvements 02 to 04
- Resolved the error regarding ":activity"-"dependent: :destroy"
- (Add a new lesson for my english teachers...)

2018-09-20 02:24 UTC, inahsanjuan requested changes

2018-09-20 02:24 UTC, inahsanjuan commented on app/controllers/sessions_controller.rb
> +		@activity = Activity.where(user_id: ids)
@nozomi-matsuoka Update to `@activities`

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +					<% end %>
@nozomi-matsuoka Try to improve indentation and spacing for this page, because there's a lot of information displayed.

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +					<% @activity.first(7).each do |activity| %>
@nozomi-matsuoka
- Change `@activity` to `@activities`
- Use `first(7)` method in the controller, instead of here.

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +					<% if activity.actionable_type == "Lesson" %>
@nozomi-matsuoka You can use this condition also, for readability:
` if activity.actionable.is_a?(Lesson)`

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +					<% @lesson = Lesson.find(activity.actionable_id)%>
@nozomi-matsuoka 
You can also use association to get lesson info by:
`activity.actionable`

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +						<p class="activity-text"><%= link_to activity.user.name, user_url(activity.user) %> learned <%= @lesson.answers.count %>/<%= @lesson.category.words.count %> words in <%= link_to @lesson.categor
@nozomi-matsuoka 
Line `41` can be improved by these lines of code:
```
<%= link_to activity.user.name, activity.user %>
learned
<%= @lesson.answers.count %>/<%= @lesson.category.words.count %>
words in
<%= link_to @lesson.category.title, category_lesson_answers_path(@lesson.category, @lesson) %>
```

Let's discuss if this is not clear.

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +					<% @follow = Relationship.find(activity.actionable_id)%>
@nozomi-matsuoka You can use this sentence to get **Relationship** object:
`@follow = activity.actionable`

2018-09-20 02:24 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
> +						<p class="activity-text"><%= link_to activity.user.name, user_url(activity.user) %> followed <%= link_to @follow.followed.name, user_url(@follow.followed) %></p>
@nozomi-matsuoka Line `45` can be improved by:
```
<%= link_to activity.user.name, activity.user %>
followed
<%= link_to @follow.followed.name, @follow.followed %>
```

2018-09-20 02:24 UTC, inahsanjuan commented on app/controllers/sessions_controller.rb
> +		@words = Word.where(id: @ids).paginate(page: params[:page], per_page: 8)
@nozomi-matsuoka 
You can improve **line 26** to **line 38** by : 
`@words = current_user.words.paginate(page: params[:page], per_page: 8)`

This is possible, if you add association in the `User` model: (_user.rb_)
`has_many :words, through: :answers`

2018-09-21 01:11 UTC, nozomi-matsuoka commented
I have revised files according to your instructions.
And also, I have changed the pagination and the header style.

2018-09-21 04:10 UTC, nozomi-matsuoka commented
I have revised files according to your instructions.

2018-09-21 04:14 UTC, inahsanjuan commented on app/controllers/sessions_controller.rb
> +		@activities = @activities[1..10]
@nozomi-matsuoka You can use `take` method

2018-09-21 04:14 UTC, inahsanjuan commented on app/controllers/users_controller.rb
> +		@activities = @activities[1..10]
@nozomi-matsuoka You can use `take` method

2018-09-21 04:14 UTC, inahsanjuan commented on app/controllers/answers_controller.rb
>   	def require_login
@nozomi-matsuoka Include this method under private

2018-09-21 04:14 UTC, inahsanjuan commented on app/views/sessions/show.html.erb
>  				<div class="col-md-5 center-block">
@nozomi-matsuoka
Try to also render using a collection : https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections

You can use **media-objects** to display each activity
https://getbootstrap.com/docs/4.1/layout/media-object/#example

2018-09-21 04:41 UTC, inahsanjuan approved these changes

2018-09-21 04:42 UTC, merged